Birthday-boy-prefix: "<gradient:#5a00ff:#e500ff>Birthday-boy</gradient>"
currentDate: "Europe/Moscow" # the timezone the plugin will focus on

Messages:
  user-no-enter-data: "<red>You haven't specified your birthday. Use <yellow>/birthday set <yyyy-mm-dd></yellow></red>"
  birthday-set-success: "<green>Your birthday has been set to: <bold>%date%</bold></green>"
  birthday-set-future-error: "<red>Invalid date. The birthday cannot be in the future.</red>"
  birthday-set-format-error: "<red>Invalid date format. Use <bold>yyyy-mm-dd</bold>.</red>"
  birthday-delete-no-permission: "<red>You don't have permission to use this command.</red>"
  birthday-delete-usage: "<red>Usage: /birthday delete <player name></red>"
  birthday-delete-success: "<green>Birthday data for <bold>%player%</bold> has been deleted.</green>"
  birthday-delete-player-not-found: "<red>Player not found.</red>"
  birthday-unknown-command: "<red>Unknown subcommand. Use <yellow>/birthday help</yellow> for more information.</red>"
  birthday-only-players: "<red>Only players can set their own birthday.</red>"
  birthday-already-set: "<red>Your birthday is already set to: <bold>%date%</bold>. It cannot be changed.</red>"

